version: '3'

services:
  frontend:
    build: .
    image: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - easychefnet
    environment:
      restart: on-failure

networks:
  easychefnet:
    driver: bridge