server:
  port: 8080
  spring:
    application:
      name: gatewayservice
    cloud:
      gateway:
        routes:
          - id: chefservice
            url: http://chefservice:8082/
            predicates:
              - Path=/user/**
          - id: recipeservice
            url: http://recipeservice:8082/
              predicates:
                - Path=/user/**